name: Download Assets
on:
  workflow_dispatch:
jobs:
  download_assets:
    runs-on: ubuntu-latest
    steps:
    - name: Env
      env:
        ASSET_FILE: assets.yml
        ASSET_PATH: asset
    - name: Checkout
      uses: actions/checkout@v3
    - name: Cache Assets
      uses: actions/cache@v3
      with:
        path: ${{ env.ASSET_PATH }}
        key: download-cache
        restore-keys: download-cache
    - name: Download Assets
      shell: pwsh
      run: |
        Install-Module -Name powershell-yaml -AcceptLicense -Force
        pwsh -File download-assets.ps1
