name: Download Assets
on:
  workflow_dispatch:
jobs:
  download_assets:
    runs-on: ubuntu-latest
    env:
        ASSET_FILE: assets.yml
        ASSET_PATH: asset
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Cache
      uses: actions/cache@v3
      env:
        A_PATH: "${{ github.workspace }}/${{ env.ASSET_PATH }}/*"
      with:
        path: ${{ env.A_PATH }}
        key: download-cache-${{ hashFiles(${{ env.A_PATH }}) }}
        restore-keys: download-cache-
    
    - name: Download
      shell: pwsh
      run: |
        Install-Module -Name powershell-yaml -AcceptLicense -Force
        pwsh -File download-assets.ps1
